# Generated by Django 5.1.5 on 2025-02-05 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hora', 'A cada Hora'), ('dia', 'Todos os dias'), ('semana', 'Semanalmente')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100, unique=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('frequencia_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.frequenciaatualizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
