# Generated by Django 5.1.5 on 2025-02-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaatualizacao',
            name='tipo',
            field=models.CharField(choices=[('A cada Hora', 'A cada Hora'), ('Todos os dias', 'Todos os dias'), ('Semanalmente', 'Semanalmente'), ('Mensalmente', 'Mensalmente')], max_length=100, unique=True),
        ),
    ]
