# Generated by Django 5.1.5 on 2025-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hora', 'A cada Hora'), ('dia', 'Todos os dias'), ('semana', 'Semanalmente')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
