# Generated by Django 5.1.5 on 2025-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_frequenciaatualizacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
