# Generated by Django 5.1.5 on 2025-02-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_frequenciaatualizacao_delete_frequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100, unique=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('frequencia_atualizacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.frequenciaatualizacao')),
            ],
        ),
    ]
