# Generated by Django 5.1.5 on 2025-02-10 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_host_ultima_atualizacao_hostshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_latency', models.FloatField(default=0.0)),
                ('load_time', models.FloatField(default=0.0)),
                ('cert_not_before', models.CharField(blank=True, max_length=20, null=True)),
                ('cert_not_after', models.CharField(blank=True, max_length=20, null=True)),
                ('cert_error', models.TextField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api.host')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HostsHistory',
        ),
    ]
