# Generated by Django 5.1.5 on 2025-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hosthistory_delete_hostshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaatualizacao',
            name='tipo',
            field=models.CharField(choices=[('A cada 2 Minutos', 'A cada 2 Minutos'), ('A cada 10 Minutos', 'A cada 10 Minutos'), ('A cada 30 Minutos', 'A cada 30 Minutos'), ('A cada Hora', 'A cada Hora'), ('Todos os dias', 'Todos os dias'), ('Semanalmente', 'Semanalmente'), ('Mensalmente', 'Mensalmente')], max_length=100, unique=True),
        ),
    ]
