# Generated by Django 5.1.3 on 2025-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_frequenciaatualizacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosthistory',
            name='avg_latency',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='hosthistory',
            name='cert_error',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='hosthistory',
            name='load_time',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
