# Generated by Django 5.1.3 on 2025-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_hosthistory_avg_latency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosthistory',
            name='load_time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
