# Generated by Django 5.1.3 on 2025-03-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_hosthistory_load_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('down_time_threshold', models.IntegerField(default=5)),
                ('response_time_threshold', models.IntegerField(default=2000)),
                ('notify_on_status', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Usuário',
                'verbose_name_plural': 'Configurações dos Usuários',
            },
        ),
    ]
