# Generated by Django 5.1.3 on 2025-03-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_alerts',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='updated_at',
        ),
    ]
