# Generated by Django 5.1.3 on 2025-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usersettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
