server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    
    # Tratamento específico para favicon.ico para evitar loops
    location = /favicon.ico {
        return 204;
        access_log off;
        log_not_found off;
    }
}
