services:
  db-postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

  frontend:
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_frontend
    ports:
      - "443:443"  # Mapeia a porta 80 do container para a 3000 localmente


  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
      - db-postgres
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    command: >
      sh -c "celery -A app worker --loglevel=info"

  celery-beat:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery_beat
    command: celery -A app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db-postgres
      - backend
      - redis
      - celery-worker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}

volumes:
  postgres_data:
  static_volume: